function A = A_mtrx(s,s_d)
%A_MTRX
%    A = A_MTRX(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Feb-2020 10:01:29

A = reshape([0.0,0.0,0.0,s_d.*cos(s).*8.547565573770493e1,0.0,0.0,0.0,1.0,0.0],[3,3]);
