function A = A_mtrx(s,s_d)
%A_MTRX
%    A = A_MTRX(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-May-2020 14:35:48

t2 = cos(s);
t3 = t2.*1.26e-2;
t4 = t3+3.1816e-3;
t5 = 1.0./t4;
t6 = sin(s);
A = reshape([s_d.*t5.*t6.*3.78e-2,0.0,0.0,s_d.*t5.*sin(s.*5.0e-1).*-6.59232e-1,0.0,0.0,s_d.^2.*t5.*t6.*-5.04e-2,1.0,0.0],[3,3]);
