function A = A_mtrx_pndlm(in1)
%A_MTRX_PNDLM
%    A = A_MTRX_PNDLM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2020 12:38:48

thta = in1(1,:);
A = reshape([0.0,cos(thta).*(-4.9e1./5.0),1.0,0.0],[2,2]);
