function A = A_mtrx(s,s_d)
%A_MTRX
%    A = A_MTRX(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Feb-2020 14:24:56

t2 = cos(s);
t3 = t2.*2.05e2;
t4 = t3+7.32e2;
t5 = 1.0./t4;
t6 = sin(s);
A = reshape([s_d.*t5.*t6.*-2.05e2,0.0,0.0,s_d.*t5.*cos(s.*(3.0./2.0)).*(-4.171212000000001e4),0.0,0.0,s_d.^2.*t5.*t6.*-8.2e2,1.0,0.0],[3,3]);
