function alfa = alpha_fcn(s)
%ALPHA_FCN
%    ALFA = ALPHA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Feb-2020 12:45:21

alfa = cos(s).*3.0875e-3+6.51975e-3;
