function alfa = alpha_fcn(s)
%ALPHA_FCN
%    ALFA = ALPHA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    22-Feb-2020 09:44:17

alfa = cos(s).*3.0875e-3+6.51975e-3;
