function alfa = alpha_fcn(s)
%ALPHA_FCN
%    ALFA = ALPHA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Feb-2020 16:41:53

alfa = cos(s).*-4.94e-3+8.693e-4;
