function B = B_mtrx(s,s_d)
%B_MTRX
%    B = B_MTRX(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Feb-2020 14:24:56

t2 = cos(s);
t3 = t2.*2.05e2;
B = [(s_d.*(t3+2.44e2).*-4.0)./(t3+7.32e2);0.0;1.0];
