function B = B_mtrx(s,s_d)
%B_MTRX
%    B = B_MTRX(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-May-2020 14:35:48

t2 = cos(s);
B = [(s_d.*(t2.*8.4e-3+6.3632e-3).*2.0)./(t2.*1.26e-2+3.1816e-3);0.0;1.0];
