function B = B_vctr_fcn(in1,in2)
%B_VCTR_FCN
%    B = B_VCTR_FCN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Feb-2020 14:24:50

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.^2;
t4 = t3.*4.2025e4;
t5 = t4-1.94956e5;
t6 = 1.0./t5;
B = [0.0;0.0;t6.*-2.44e6;t6.*(t2.*2.885118511284224e19+3.433994715870003e19).*7.105427357601002e-14];
