function B = B_vctr_fcn(in1,in2)
%B_VCTR_FCN
%    B = B_VCTR_FCN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-May-2020 14:35:41

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.^2;
t4 = t3.*8.82e9;
t5 = t4-2.2872653641e10;
t6 = 1.0./t5;
B = [0.0;0.0;t6.*-7.954e11;t6.*(t2.*1.05e11+7.954e10).*1.0e1];
