function f = f_fcn(in1,in2,u)
%F_FCN
%    F = F_FCN(IN1,IN2,U)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-May-2020 14:35:42

q1 = in1(1,:);
q2 = in1(2,:);
qd1 = in2(1,:);
qd2 = in2(2,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = qd1.^2;
t5 = t2.^2;
t6 = t5.*8.82e9;
t7 = t6-2.2872653641e10;
t8 = 1.0./t7;
t9 = u.*7.954e10;
t10 = q1+q2;
t11 = cos(t10);
t12 = cos(q1);
t13 = t12.*-9.4925863647e10;
t14 = qd2.^2;
t15 = t3.*t14.*6.68136e8;
t16 = t2.*t11.*3.460968e10;
t17 = qd1.*qd2.*t3.*1.336272e9;
f = [qd1;qd2;t8.*(t9+t13+t15+t16+t17+t3.*t4.*6.68136e8+t2.*t3.*t4.*8.82e8).*-1.0e1;t8.*(t9+t11.*1.18481151033e11+t13+t15+t16+t17+t3.*t4.*3.687533325e9-t2.*t12.*1.2531073275e11+t2.*u.*1.05e11+t2.*t3.*t4.*1.764e9+t2.*t3.*t14.*8.82e8+qd1.*qd2.*t2.*t3.*1.764e9).*1.0e1];
