function gma = gama_fcn(s)
%GAMA_FCN
%    GMA = GAMA_FCN(S)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    02-Mar-2020 15:08:21

gma = cos(s.*(3.0./2.0)-pi./2.0).*2.42307e-1;
