function D_thta = M_mtrx_fcn(in1)
%M_MTRX_FCN
%    D_THTA = M_MTRX_FCN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Feb-2020 14:24:48

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*2.05e-2;
t4 = t3+2.44e-2;
D_thta = reshape([t2.*(4.1e1./1.0e3)+1.043e-1,t4,t4,2.44e-2],[2,2]);
