function D_thta = M_mtrx_fcn(in1)
%M_MTRX_FCN
%    D_THTA = M_MTRX_FCN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Feb-2020 10:16:51

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*6.175e-3;
t4 = t3+4.3465e-3;
D_thta = reshape([t2.*1.235e-2+3.0602665e-2,t4,t4,4.3465e-3],[2,2]);
