function M_sym = M_mtrx_fcn_pndlm(in1)
%M_MTRX_FCN_PNDLM
%    M_SYM = M_MTRX_FCN_PNDLM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2020 12:38:47

M_sym = 1.0e1;
