function D_thta = M_mtrx_fcn(in1)
%M_MTRX_FCN
%    D_THTA = M_MTRX_FCN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-May-2020 14:35:39

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*8.4e-3;
t4 = t3+6.3632e-3;
D_thta = reshape([t2.*1.68e-2+3.5119365e-2,t4,t4,6.3632e-3],[2,2]);
