function N = N_fcn(s,s_d)
%N_FCN
%    N = N_FCN(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Feb-2020 16:41:55

t2 = cos(s);
N = (t2.*1.52e33-2.674769230769231e32)./(t2.^2.*1.17325e31-3.511459113e31);
