function N = N_fcn(s,s_d)
%N_FCN
%    N = N_FCN(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    18-Feb-2020 14:24:54

t2 = cos(s);
N = ((t2.*2.05e2+7.32e2).*-5.0e3)./(t2.^2.*4.2025e4-1.94956e5);
