function N = N_fcn(s,s_d)
%N_FCN
%    N = N_FCN(S,S_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Mar-2020 18:02:04

t2 = cos(s);
N = -1.337384615384615e11./(t2.^2.*1.17325e9-3.511459113e9);
