function n_sym = n_vctr_fcn_pndlm(in1)
%N_VCTR_FCN_PNDLM
%    N_SYM = N_VCTR_FCN_PNDLM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Apr-2020 12:38:48

thta = in1(1,:);
n_sym = sin(thta).*9.8e1;
