function out1 = U_ff(s,s_d,y,y_d)
%U_FF
%    OUT1 = U_FF(S,S_D,Y,Y_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Feb-2020 17:55:57

t2 = cos(s);
t3 = s.*5.0e-1;
t4 = sin(s);
t5 = s_d.^2;
t6 = s.*2.0;
t7 = y_d.^2;
t8 = sin(t6);
out1 = ((t2.^2.*1.17325e9-3.511459113e9).*(sin(t3-y.*1.0).*2.081137545e31+sin(s.*2.5+y).*1.3811499e31+sin(s.*1.5+y).*1.83397173048e31-sin(t3+y).*7.408159579523077e31+t4.*t5.*1.3643108175e30+t4.*t7.*1.49323527e30+t5.*t8.*3.51975e29+t7.*t8.*4.693e29+s_d.*t4.*y_d.*2.48423727e30+s_d.*t8.*y_d.*7.0395e29).*-2.5e20)./((cos(t6).*2.3465e29-1.1699336452e30).*(t2.*2.375e31+5.015192307692308e31));
