function out1 = U_ff(s,s_d,y,y_d)
%U_FF
%    OUT1 = U_FF(S,S_D,Y,Y_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Feb-2020 16:41:56

t2 = cos(s);
t3 = y.*-1.0;
t4 = sin(s);
t5 = s_d.^2;
t6 = s.*2.0;
t7 = y_d.^2;
t8 = sin(t6);
out1 = -((t2.^2.*1.17325e31-3.511459113e31).*(sin(s.*1.2+y).*2.3019165e34+sin(s.*8.0e-1+t3).*1.234693263253846e35-sin(s.*2.0e-1+y).*3.66794346096e35-sin(s.*1.8+t3).*4.16227509e35+t4.*t5.*1.2737965256e34+t4.*t7.*1.91288504e34-t5.*t8.*2.8158e32+t7.*t8.*1.759875e33-s_d.*t4.*y_d.*3.225783064e34+s_d.*t8.*y_d.*1.8772e33))./((cos(t6).*2.933125e33-1.4624170565e34).*(t2.*1.52e33-2.674769230769231e32));
