function out1 = U_ff(s,s_d,y,y_d)
%U_FF
%    OUT1 = U_FF(S,S_D,Y,Y_D)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Feb-2020 10:01:28

t2 = cos(s);
t3 = s.*2.0;
t4 = sin(s);
t5 = y_d.^2;
out1 = ((t2.^2.*1.72233606557377e-2-7.99e-2).*(sin(t3+y).*(-7.521525597306808e19)+sin(y).*6.343443071975605e20+t4.*t5.*3.519844583766753e18+s_d.^2.*t4.*3.519844583766753e18+t5.*sin(t3).*1.478623237033165e18+s_d.*t4.*y_d.*7.039689167533507e18).*(-2.842170943040401e-14))./(cos(t3).*4.2025e4-3.47887e5);
