function out1 = U_full(s,s_d,y,y_d,v)
%U_FULL
%    OUT1 = U_FULL(S,S_D,Y,Y_D,V)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-May-2020 14:35:46

t2 = cos(s);
t3 = s.*5.0e-1;
t4 = s_d.^2;
t5 = s.*2.0;
t6 = s.*1.0;
t7 = sin(t6);
t8 = y_d.^2;
t9 = sin(t5);
out1 = ((t2.^2.*8.82e9-2.2872653641e10).*(v-(cos(t3-y).*-1.67477353974e12-cos(t3+y).*1.730484e11+cos(s.*2.5-y).*1.87966099125e12+cos(s.*1.5-y).*7.7621023647e11+t4.*t7.*2.054796594375e11+t4.*t9.*1.323e10+t7.*t8.*9.726327975e10+t8.*t9.*1.764e10-s_d.*t7.*y_d.*2.7842711925e11-s_d.*t9.*y_d.*2.646e10)./(cos(t5).*8.82e9-3.6925307282e10)))./(t2.*1.575e12+3.977e11);
