function out1 = U_full(s,s_d,y,y_d,v)
%U_FULL
%    OUT1 = U_FULL(S,S_D,Y,Y_D,V)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Feb-2020 13:24:10

t2 = s.*5.0e-1;
t3 = sin(s);
t4 = s_d.^2;
t5 = s.*2.0;
t6 = y_d.^2;
t7 = sin(t5);
t8 = cos(s);
out1 = ((t8.^2.*1.17325e9-3.511459113e9).*(v+((sin(t2-y.*1.0).*2.081137545e31+sin(s.*2.5+y).*1.3811499e31+sin(s.*1.5+y).*1.83397173048e31-sin(t2+y).*7.408159579523077e31+t3.*t4.*1.3643108175e30+t3.*t6.*1.49323527e30+t4.*t7.*3.51975e29+t6.*t7.*4.693e29+s_d.*t3.*y_d.*2.48423727e30+s_d.*t7.*y_d.*7.0395e29).*1.0)./(cos(t5).*2.3465e29-1.1699336452e30)).*-2.5e20)./(t8.*2.375e31+5.015192307692308e31);
