<?xml version="1.0" encoding="utf-8"?>	
	<robot name="pndbt" xmlns:xacro="http://ros.org/wiki/xacro">

<!--SOME PROPERTIES!-->	
		<xacro:property name="table_length" value="3" />
		<xacro:property name="table_width" value="1.5" />
		<xacro:property name="table_height" value="0.05" />

		<xacro:property name="stand_height" value="0.2" />
		<xacro:property name="stand_length" value="0.4" />
		<xacro:property name="stand_width" value="0.15" />
		
		<xacro:property name="rotor_length" value="0.1" />
		<xacro:property name="rotor_radius" value="0.05" />

		<xacro:property name="link1_height" value="0.05" />
		<xacro:property name="link1_length" value="0.250" />
		<xacro:property name="link1_width" value="0.10" />

		<xacro:property name="link2_height" value="0.05" />
		<xacro:property name="link2_length" value="0.250" />
		<xacro:property name="link2_width" value="0.10" />

		<xacro:property name="links_offset" value="0.06" />



		<gazebo reference="table_down">
		  <material>Gazebo/Grey</material>
		</gazebo>

		<gazebo reference="table_upper">
		  <material>Gazebo/GreyTransparent</material>
		</gazebo>


		<gazebo reference="stand">
		  <material>Gazebo/Black</material>
		</gazebo>

		<gazebo reference="rotor">
		  <material>Gazebo/Blue</material>
		</gazebo>

		<gazebo reference="link1">
		  <material>Gazebo/Yellow</material>
		</gazebo>

		<gazebo reference="link2">
		  <material>Gazebo/Red</material>
		</gazebo>


   
		<link name ="world"/>

      <joint name="grounding" type="fixed">
        <parent link="world"/>
        <child link="table"/>
        <origin
          xyz="0 0 1"
          rpy="0 0 0" />
      </joint>


	 	<link name="table">
	   		<visual>
	    			<geometry>
	        			<box size ="${table_width} ${table_length} ${table_height}"/>
	    			</geometry>
	    			<origin xyz ="0 0 -${table_height/2}"/>   
	    			<material name="blue">
        				<color rgba="0 0 0.8 1"/>
     	    			</material>
	   		</visual>
			<inertial>
				<mass value="100"/>
				<inertia
				      ixx="1.0" ixy="0.0" ixz="0.0"
				      iyy="1.0" iyz="0.0"
				      izz="1.0"/>
			</inertial>
	 	</link>

<!--Stand!-->
	 	<link name="stand">
	   		<visual>
	    			<geometry>
	        			<box size ="${stand_length} ${stand_width} ${stand_height}"/>
	    			</geometry>
	    			<origin xyz ="0 0 ${stand_height/2}"/>   
	    			<material name="blue">
        				<color rgba="0 0 0.8 1"/>
     	    			</material>
	   		</visual>
			<inertial>
				<mass value="100"/>
				<inertia
				      ixx="1.0" ixy="0.0" ixz="0.0"
				      iyy="1.0" iyz="0.0"
				      izz="1.0"/>
			</inertial>
	 	</link>
	 
	 	<joint name="table_upper_stand" type="fixed">
	 		<parent link="table"/>
	 		<child link="stand"/>
			<origin rpy="0 0 0" xyz="${table_width/2-stand_length/2} 0 0"/>
	 	</joint>

<!--Rotor!-->
	 	<link name="rotor">
	   		<visual>
	    			<geometry>
	        			<cylinder length ="${rotor_length}" radius="${rotor_radius}"/>
	    			</geometry>
	    			<origin rpy="0 1.57075 0" xyz ="0 0 0"/>   
	    			<material name="blue">
        				<color rgba="0 0 0.8 1"/>
     	    			</material>
	   		</visual>
			<inertial>
				<mass value="0.10"/>
				<inertia
				      ixx="1.0" ixy="0.0" ixz="0.0"
				      iyy="1.0" iyz="0.0"
				      izz="1.0"/>
			</inertial>
	 	</link>
	 
	 	<joint name="stand_rotor" type="fixed">
		 	<parent link="stand"/>
		 	<child link="rotor"/>
			<origin rpy="0 0 0" xyz="${stand_length/2+rotor_length/2} 0 ${stand_height/2}"/>
	 	</joint>

	 	<link name="link1">
	   		<visual>
	    			<geometry>
	        			<box size ="${link1_length} ${link1_width} ${link1_height}"/>
	    			</geometry>
	    			<origin rpy="0 0 0" xyz ="${link1_length/2} 0 0"/>   
	    			<material name="blue">
        				<color rgba="0 0 0.8 1"/>
     	    			</material>
	   		</visual>
			<inertial>
				<origin rpy="0 0 0" xyz ="-0.0284 0.0905 0"/>   
				<mass value="1.4957"/>
				<inertia
				      ixx="1.0" ixy="0.0" ixz="0.0"
				      iyy="1.0" iyz="0.0"
				      izz="6.43665747695468e-06"/>
			</inertial>
	 	</link>
	 
	 	<joint name="j1_shoulder" type="continuous">
		 	<parent link="rotor"/>
		 	<child link="link1"/>
		 	<axis xyz="0 0 1"/>
			<origin rpy="1.570796 0 1.570796" xyz="${rotor_length/2+link1_height/2} 0 0"/>
			<!--<limit effort="1000.0" lower="-3.1416" upper="3.1416" velocity="0.5"/>!-->
			<dynamics damping="0.000"/>
	 	</joint>

	 	<link name="link2">
	   		<visual>
	    			<geometry>
	        			<box size ="${link2_length} ${link2_width} ${link2_height}"/>
	    			</geometry>
	    			<origin xyz ="${link2_length/2} 0 0"/>   
	    			<material name="blue">
        				<color rgba="0 0 0.8 1"/>
     	    			</material>
	   		</visual>
			<inertial>
				<!-- <origin rpy="0 0 0" xyz ="0 0 -0.095"/> -->
				<origin rpy="0 0 0" xyz ="0.1089 0.0092 0"/>   <!-- with imu -->  
				<!-- <mass value="0.26"/> -->
				<mass value="0.1903"/> <!-- with imu -->
				<inertia
				      ixx="1.0" ixy="0.0" ixz="0.0"
				      iyy="1.0" iyz="0.0"
				      izz="6.43665747695468e-06"/>
			</inertial>
	 	</link>
	 
	 	<joint name="j2_elbow" type="continuous">
			<axis xyz="0 0 1"/>
			<!--<limit effort="1000.0" lower="-3.1416" upper="3.1416" velocity="0.5"/>!-->
		 	<parent link="link1"/>
		 	<child link="link2"/>
			<origin xyz="${link1_length} 0 ${links_offset}"/>
			<dynamics damping="0.000"/>
	 	</joint>
	
</robot>
